# fly.toml app configuration file generated for discord-wordle-clone on 2023-08-01T16:56:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-wordle-clone"
primary_region = "den"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false  # prevent automatic suspension
  min_machines_running = 1  # keep a machine running at all times
